import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { Providers } from "./store/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body className="min-h-screen flex flex-col bg-blue-500/20">
        <Providers>
        <Header />
        <main className="flex-1 container mx-auto p-4">{children}</main>
         </Providers>
      </body>
    </html>
  );
}
